# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        files: ^backend/
        additional_dependencies:
         - types-paramiko
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff-check  # Linter
        files: ^backend/
        args: [ --fix, --select, "I" ]
      - id: ruff-format  # Formatter
        files: ^backend/
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        language: system
        files: ^frontend/src
        pass_filenames: false
        entry: |
          bash -c "cd frontend && npm run lint"
      - id: prettier
        name: prettier
        language: system
        files: ^frontend/src
        pass_filenames: false
        entry: |
          bash -c "cd frontend && npm run format"
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
        exclude: ^frontend/package(-lock)?\.json$
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
