FROM nvcr.io/nvidia/cuda:13.1.1-runtime-ubuntu24.04

########################################
# RCP CaaS requirement
########################################
# Mapping needed to access files from the external storage
ARG LDAP_USERNAME
ARG LDAP_UID
ARG LDAP_GROUPNAME
ARG LDAP_GID
RUN groupadd ${LDAP_GROUPNAME} --gid ${LDAP_GID}
RUN useradd -m -s /bin/bash -g ${LDAP_GROUPNAME} -u ${LDAP_UID} ${LDAP_USERNAME}
RUN mkdir -p /home/${LDAP_USERNAME}

########################################
# Setup
########################################
RUN apt update && \
    apt install -y \
    curl \
    ca-certificates \
    git \
    build-essential \
	cmake \
    libvulkan1 \
    vulkan-tools \
    mesa-vulkan-drivers \
    nvidia-driver-570

COPY backend/scripts/linux/install_brush.sh /home/${LDAP_USERNAME}/install_brush.sh
RUN /home/${LDAP_USERNAME}/install_brush.sh
RUN apt clean && rm -rf /var/lib/apt/lists/*
RUN ln -s /external/bin/brush /usr/local/bin/brush

USER ${LDAP_USERNAME}
